package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const goodModuleDir = "../check/testdata/good"

// runCheckCommand drives the real `cuefn check` command and returns its
// output.
func runCheckCommand(t *testing.T, args ...string) (string, error) {
	t.Helper()
	var out bytes.Buffer
	root := NewRootCommand(Options{Out: &out, Err: &out})
	root.SetArgs(append([]string{"check"}, args...))
	err := root.ExecuteContext(context.Background())
	return out.String(), err
}

// checkModuleDir clones the good fixture module into a temp dir so a test can
// break it without touching the shared fixture.
func checkModuleDir(t *testing.T, extraFiles map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.CopyFS(dir, os.DirFS(goodModuleDir)))
	for name, content := range extraFiles {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600))
	}
	return dir
}

func TestCheckCommand_AllPass(t *testing.T) {
	t.Parallel()

	out, err := runCheckCommand(t, "--dir", goodModuleDir)
	require.NoError(t, err)
	assert.Contains(t, out, "PASS fmt")
	assert.Contains(t, out, "PASS vet")
	assert.Contains(t, out, "PASS xrd")
	assert.Contains(t, out, "3 passed, 0 failed, 0 seeded, 0 updated")
}

func TestCheckCommand_UnformattedFileFailsFmtOnly(t *testing.T) {
	t.Parallel()

	dir := checkModuleDir(t, map[string]string{
		"extra.cue": "package good\n\nextra:    \"spaced\"\n",
	})

	out, err := runCheckCommand(t, "--dir", dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "1 of 3 checks failed")
	assert.Contains(t, out, "FAIL fmt")
	assert.Contains(t, out, "extra.cue")
	assert.Contains(t, out, "run `cue fmt` to fix")
	assert.Contains(t, out, "PASS vet")
	assert.Contains(t, out, "PASS xrd")
}

func TestCheckCommand_LoadFailureFailsVetAndXRD(t *testing.T) {
	t.Parallel()

	dir := checkModuleDir(t, map[string]string{
		"conflict.cue": "package good\n\nboom: int\nboom: \"not an int\"\n",
	})

	out, err := runCheckCommand(t, "--dir", dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "2 of 3 checks failed")
	assert.Contains(t, out, "PASS fmt")
	assert.Contains(t, out, "FAIL vet")
	assert.Contains(t, out, "conflicting values")
	assert.Contains(t, out, "FAIL xrd")
	assert.Contains(t, out, "module did not load; see vet")
}

func TestCheckCommand_DisjunctionFailsXRD(t *testing.T) {
	t.Parallel()

	out, err := runCheckCommand(t, "--dir", "../check/testdata/disjunction")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "1 of 3 checks failed")
	assert.Contains(t, out, "PASS fmt")
	assert.Contains(t, out, "PASS vet")
	assert.Contains(t, out, "FAIL xrd")
	assert.Contains(t, out, "type-crossing disjunction")
	assert.Contains(t, out, "port")
}

func TestCheckCommand_MissingModuleDirErrors(t *testing.T) {
	t.Parallel()

	_, err := runCheckCommand(t, "--dir", filepath.Join(t.TempDir(), "nope"))
	require.Error(t, err)
}

func TestCheckCommand_GoldenLifecycle(t *testing.T) {
	t.Setenv("CI", "0")

	golden := filepath.Join(t.TempDir(), "xrd.yaml")

	// First run seeds the golden with the machine-owned header and exits
	// non-zero so a fresh golden is always reviewed.
	out, err := runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "seeded the XRD golden")
	assert.Contains(t, out, "SEED xrd")
	seeded, readErr := os.ReadFile(golden)
	require.NoError(t, readErr)
	assert.Contains(t, string(seeded), "# Generated by cuefn check; DO NOT EDIT.")
	assert.Contains(t, string(seeded), "cuefn check --xrd "+golden+" --update")

	// The seeded golden passes as-is.
	out, err = runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden)
	require.NoError(t, err)
	assert.Contains(t, out, "PASS xrd")

	// Drift fails with a labeled line diff.
	drifted := strings.ReplaceAll(string(seeded), "xgadgets", "xwidgets")
	require.NoError(t, os.WriteFile(golden, []byte(drifted), 0o600))
	out, err = runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden)
	require.Error(t, err)
	assert.Contains(t, out, "FAIL xrd")
	assert.Contains(t, out, "golden mismatch (-golden +generated):")
	assert.Contains(t, out, "- ")
	assert.Contains(t, out, "+ ")

	// --update re-blesses the drifted golden, and the run passes afterward.
	out, err = runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden, "--update")
	require.NoError(t, err)
	assert.Contains(t, out, "UPDATE xrd")
	out, err = runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden)
	require.NoError(t, err)
	assert.Contains(t, out, "PASS xrd")
}

func TestCheckCommand_CIRefusesSeedAndUpdate(t *testing.T) {
	t.Setenv("CI", "0")

	golden := filepath.Join(t.TempDir(), "xrd.yaml")

	_, err := runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden, "--ci", "--update")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "--update is not allowed in CI mode")

	out, err := runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden, "--ci")
	require.Error(t, err)
	assert.Contains(t, out, "FAIL xrd")
	assert.Contains(t, out, "does not exist; run `cuefn check` locally to seed it")
	assert.NoFileExists(t, golden, "CI mode must not write goldens")
}

func TestCheckCommand_HeaderlessGoldenMatches(t *testing.T) {
	t.Parallel()

	// A golden written by `cuefn generate --output` has no header; the
	// comment-stripping comparison must accept it unchanged.
	var out bytes.Buffer
	root := NewRootCommand(Options{Out: &out, Err: &out})
	golden := filepath.Join(t.TempDir(), "xrd.yaml")
	root.SetArgs([]string{"generate", "ignored", "--dir", goodModuleDir, "--output", golden})
	require.NoError(t, root.ExecuteContext(context.Background()))

	res, err := runCheckCommand(t, "--dir", goodModuleDir, "--xrd", golden)
	require.NoError(t, err)
	assert.Contains(t, res, "PASS xrd")
}
