package check

import (
	"bytes"
	"fmt"
	"strings"

	"cuelang.org/go/cue"

	"github.com/meigma/crossplane-cuefn/internal/schema"
	"github.com/meigma/crossplane-cuefn/internal/textdiff"
)

// goldenHeader opens every machine-written golden file.
const goldenHeader = "# Generated by cuefn check; DO NOT EDIT."

// XRD generates the module's XRD YAML and, when a golden is supplied,
// compares the generation against it. The comparison is byte-exact after
// normalizing line endings and stripping leading full-line comments from both
// sides, so a machine-written header (see [GoldenBytes]) and a headerless
// `cuefn generate --output` file both compare equal to the same generation.
// It returns the generated YAML and a diff that is "" when the golden matches
// or none was supplied; on mismatch the diff is a full line diff between the
// stripped golden and the stripped generation.
func XRD(module cue.Value, golden []byte, haveGolden bool) ([]byte, string, error) {
	generated, err := schema.GenerateXRDYAML(module)
	if err != nil {
		return nil, "", fmt.Errorf("cannot generate XRD: %w", err)
	}
	if !haveGolden {
		return generated, "", nil
	}

	want := stripLeadingComments(textdiff.Normalize(golden))
	got := stripLeadingComments(textdiff.Normalize(generated))
	if want == got {
		return generated, "", nil
	}
	return generated, textdiff.Lines(want, got), nil
}

// GoldenBytes renders the golden-file content for a generated XRD: the
// machine-owned header naming the re-bless command, then the generation
// verbatim. The header is comment-only, so [XRD]'s stripped comparison
// accepts the exact file this writes.
func GoldenBytes(generated []byte, xrdPath string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s\n# Re-bless with: cuefn check --xrd %s --update\n", goldenHeader, xrdPath)
	b.Write(generated)
	return b.Bytes()
}

// stripLeadingComments drops full-line comments and blank lines at the top of
// a normalized text, so machine-written headers never participate in the
// golden comparison.
func stripLeadingComments(s string) string {
	for {
		line, rest, found := strings.Cut(s, "\n")
		trimmed := strings.TrimSpace(line)
		if found && (trimmed == "" || strings.HasPrefix(trimmed, "#")) {
			s = rest
			continue
		}
		return s
	}
}
